[project]
name = "algorithm"
version = "0.1.0"
description = ""
authors = [{ name = "AgrospAI", email = "agrospai@udl.cat" }]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "pytest>=8.3.4,<9",
    "oceanprotocol-job-details==0.1.1",
    "orjson>=3.10.15,<4",
    "pandas>=2.3.0",
    "numpy>=2.2.6",
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
    "reportlab>=4.4.1",
    "datetime>=5.5",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["src"]
