[project]
name = "algorithm"
version = "0.1.0"
description = ""
authors = [{ name = "AgrospAI", email = "agrospai@udl.cat" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "pandas>=2.3.3",
    "ydata-profiling>=4.17.0",
    "setuptools>=80.9.0",
    "ocean-runner>=0.3.11",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = ["mypy<1.18.0", "pandas-stubs>=3.0.0.260204", "pytest>=8.4.2"]
