[project]
name = "algorithm"
version = "0.1.0"
description = ""
authors = [{ name = "AgrospAI", email = "agrospai@udl.cat" }]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "numpy==1.26.0",
    "pytest>=8.3.4,<9",
    "oceanprotocol-job-details==0.0.11",
    "scikit-learn>=1.6.1,<2",
    "pandas>=2.2.3,<3",
    "cloudpickle>=3.1.1,<4",
    "orjson>=3.10.15,<4",
]

[tool.poetry]
package-mode = false

[tool.pytest.ini_options]
pythonpath = ["src"]
