# Use this docker-compose to test the algorithm locally
services:
  algorithm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount input/output directories
      - ./_data/inputs:/data/inputs:ro
      - ./_data/ddos:/data/ddos:ro
      - ./_data/outputs:/data/outputs:rw
      - ./_data/logs:/data/logs:rw
      # Mount source code for development
      - ./algorithm/src:/algorithm/src/
      - ./algorithm/tests:/algorithm/tests/
      - ./entrypoint.sh:/algorithm/entrypoint.sh
    environment:
      # Development mode
      DEV: 1
      DIDS: '["fe7eea9ef883bbf9bbe764de3445b37b5f74d85c8fe69490fc87bd78985610ec"]'
      secret: "1234"
      TRANSFORMATION_DID: "1234"